cache_enabled: true
# Possible value: internal, redis
cache_backend: internal
# Optional redis uri
redis_uri: redis://127.0.0.1:6379
# Maxmind GeoIP database path
geoip_city_db_path: /path/to/GeoIPCity.dat
log_level: info
dns53:
  enabled: true
  listen: tcp://:53,udp://53
  # only tcp dns53 upstream is supported
  upstream: tcp://8.8.8.8:53,tcp://8.8.8.8:53
  # Possible value: doh, dns53, doh_json
  upstream_proto: dns53
  ecs_ip_2nd: 192.0.2.1
doh:
  enabled: true
  listen: 127.0.0.1:443
  upstream: https://dns.google/dns-query
  # Possible value: doh, dns53, doh_json
  upstream_proto: doh
  path: /dns-query
  ecs_ip_2nd: 192.0.2.1
  use_tls: true
  tls_cert_file: /path/to/cert.pem
  tls_key_file: /path/to/key.pem
# when query name matched name_regex, will skip the query with ecs ips that have specified geo country codes
names_in_jail:
  - name_regex: ^([^\.\s]+\.)*apple\.com\.$
    country_codes: RU
  - name_regex: ^([^\.\s]+\.)*linkedin\.com\.$
    country_codes: CN,RU
