cache_enabled: true
# Possible value: internal, redis
cache_backend: internal
# Optional redis uri
redis_uri: redis://127.0.0.1:6379
# Maxmind GeoIP database path
geoip_city_db_path: /path/to/GeoIPCity.dat
log_level: info
# upstream host resolver
upstream_host_resolver: tcp://127.0.0.1:1253
dns53:
  enabled: true
  listen: tcp://:53,udp://53
  # only tcp dns53 upstream is supported
  upstream: tcp://8.8.8.8:53,tcp://8.8.8.8:53
  upstream_fallback: tcp://8.8.8.8:53,tcp://8.8.8.8:53
  # Possible value: doh, dns53, doh_json
  upstream_proto: dns53
  # use client ip as ecs
  use_client_ip: true
  1st_ecs_ip: 192.0.2.1
  2nd_ecs_ip: 192.0.2.1
  fixed_resolving:
    - name_regex: ^([^\.\s]+\.)*google\.com\.$
      server: tcp://8.8.8.8
    - name_regex: ^([^\.\s]+\.)*gmail\.com\.$
      server: tcp://8.8.8.8
doh:
  enabled: true
  listen: 127.0.0.1:443
  upstream: https://dns.google/dns-query
  upstream_fallback: https://dns.google/dns-query
  # Possible value: doh, dns53, doh_json
  upstream_proto: doh
  path: /dns-query
  # use client ip as ecs
  use_client_ip: true
  1st_ecs_ip: 192.0.2.1
  2nd_ecs_ip: 192.0.2.1
  use_tls: true
  tls_cert_file: /path/to/cert.pem
  tls_key_file: /path/to/key.pem
  fixed_resolving:
    - name_regex: ^([^\.\s]+\.)*google\.com\.$
      server: https://dns.google/dns-query
    - name_regex: ^([^\.\s]+\.)*gmail\.com\.$
      server: https://dns.google/dns-query
# when query name matched name_regex, will skip the query with ecs ips that have specified geo country codes
names_in_jail:
  # apple
  - name_regex: ^([^\.\s]+\.)*apple\.com\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*cdn-apple\.com\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*apple-cloudkit\.com\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*icloud.\.com\.$
    country_codes: CN
  # linkedin
  - name_regex: ^([^\.\s]+\.)*linkedin\.com\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*licdn\.com\.$
    country_codes: CN
  # google
  - name_regex: ^([^\.\s]+\.)*google-analytics\.com\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*doubleclick\.net\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*googletagmanager\.com\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*googletagservices\.com\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*google\.com\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*googleapis\.com\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*googleusercontent\.com\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*gstatic\.com\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*gmail\.com\.$
    country_codes: CN
  - name_regex: ^([^\.\s]+\.)*googlemail\.com\.$
    country_codes: CN
